//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.MainService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdminDto", Namespace="http://schemas.datacontract.org/2004/07/GaiWcfService.Dto")]
    [System.SerializableAttribute()]
    public partial class AdminDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeDto", Namespace="http://schemas.datacontract.org/2004/07/GaiWcfService.Dto")]
    [System.SerializableAttribute()]
    public partial class EmployeeDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int certificateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime hireDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string patronymicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.MainService.Post rankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int certificateId {
            get {
                return this.certificateIdField;
            }
            set {
                if ((this.certificateIdField.Equals(value) != true)) {
                    this.certificateIdField = value;
                    this.RaisePropertyChanged("certificateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime hireDate {
            get {
                return this.hireDateField;
            }
            set {
                if ((this.hireDateField.Equals(value) != true)) {
                    this.hireDateField = value;
                    this.RaisePropertyChanged("hireDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string patronymic {
            get {
                return this.patronymicField;
            }
            set {
                if ((object.ReferenceEquals(this.patronymicField, value) != true)) {
                    this.patronymicField = value;
                    this.RaisePropertyChanged("patronymic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.MainService.Post rank {
            get {
                return this.rankField;
            }
            set {
                if ((this.rankField.Equals(value) != true)) {
                    this.rankField = value;
                    this.RaisePropertyChanged("rank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Post", Namespace="http://schemas.datacontract.org/2004/07/GaiWcfService.Dto")]
    public enum Post : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PRIVATE = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERGEANT = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LEIUTENANT = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentDto", Namespace="http://schemas.datacontract.org/2004/07/GaiWcfService.Dto")]
    [System.SerializableAttribute()]
    public partial class PaymentDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isPaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime paydayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int violatorIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isPaid {
            get {
                return this.isPaidField;
            }
            set {
                if ((this.isPaidField.Equals(value) != true)) {
                    this.isPaidField = value;
                    this.RaisePropertyChanged("isPaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime payday {
            get {
                return this.paydayField;
            }
            set {
                if ((this.paydayField.Equals(value) != true)) {
                    this.paydayField = value;
                    this.RaisePropertyChanged("payday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int violatorId {
            get {
                return this.violatorIdField;
            }
            set {
                if ((this.violatorIdField.Equals(value) != true)) {
                    this.violatorIdField = value;
                    this.RaisePropertyChanged("violatorId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShiftDto", Namespace="http://schemas.datacontract.org/2004/07/GaiWcfService.Dto")]
    [System.SerializableAttribute()]
    public partial class ShiftDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime endField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int responsibleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime startField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime end {
            get {
                return this.endField;
            }
            set {
                if ((this.endField.Equals(value) != true)) {
                    this.endField = value;
                    this.RaisePropertyChanged("end");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int responsibleId {
            get {
                return this.responsibleIdField;
            }
            set {
                if ((this.responsibleIdField.Equals(value) != true)) {
                    this.responsibleIdField = value;
                    this.RaisePropertyChanged("responsibleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime start {
            get {
                return this.startField;
            }
            set {
                if ((this.startField.Equals(value) != true)) {
                    this.startField = value;
                    this.RaisePropertyChanged("start");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ViolationDto", Namespace="http://schemas.datacontract.org/2004/07/GaiWcfService.Dto")]
    [System.SerializableAttribute()]
    public partial class ViolationDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string car_numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double locationEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double locationNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double penaltyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int violationTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int violatorIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string car_number {
            get {
                return this.car_numberField;
            }
            set {
                if ((object.ReferenceEquals(this.car_numberField, value) != true)) {
                    this.car_numberField = value;
                    this.RaisePropertyChanged("car_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double locationE {
            get {
                return this.locationEField;
            }
            set {
                if ((this.locationEField.Equals(value) != true)) {
                    this.locationEField = value;
                    this.RaisePropertyChanged("locationE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double locationN {
            get {
                return this.locationNField;
            }
            set {
                if ((this.locationNField.Equals(value) != true)) {
                    this.locationNField = value;
                    this.RaisePropertyChanged("locationN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double penalty {
            get {
                return this.penaltyField;
            }
            set {
                if ((this.penaltyField.Equals(value) != true)) {
                    this.penaltyField = value;
                    this.RaisePropertyChanged("penalty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int violationTypeId {
            get {
                return this.violationTypeIdField;
            }
            set {
                if ((this.violationTypeIdField.Equals(value) != true)) {
                    this.violationTypeIdField = value;
                    this.RaisePropertyChanged("violationTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int violatorId {
            get {
                return this.violatorIdField;
            }
            set {
                if ((this.violatorIdField.Equals(value) != true)) {
                    this.violatorIdField = value;
                    this.RaisePropertyChanged("violatorId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ViolationTypeDto", Namespace="http://schemas.datacontract.org/2004/07/GaiWcfService.Dto")]
    [System.SerializableAttribute()]
    public partial class ViolationTypeDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double minPenaltyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double minPenalty {
            get {
                return this.minPenaltyField;
            }
            set {
                if ((this.minPenaltyField.Equals(value) != true)) {
                    this.minPenaltyField = value;
                    this.RaisePropertyChanged("minPenalty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ViolatorDto", Namespace="http://schemas.datacontract.org/2004/07/GaiWcfService.Dto")]
    [System.SerializableAttribute()]
    public partial class ViolatorDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double actual_penaltyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double paid_penaltyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passportIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string patronymicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double actual_penalty {
            get {
                return this.actual_penaltyField;
            }
            set {
                if ((this.actual_penaltyField.Equals(value) != true)) {
                    this.actual_penaltyField = value;
                    this.RaisePropertyChanged("actual_penalty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double paid_penalty {
            get {
                return this.paid_penaltyField;
            }
            set {
                if ((this.paid_penaltyField.Equals(value) != true)) {
                    this.paid_penaltyField = value;
                    this.RaisePropertyChanged("paid_penalty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string passportId {
            get {
                return this.passportIdField;
            }
            set {
                if ((object.ReferenceEquals(this.passportIdField, value) != true)) {
                    this.passportIdField = value;
                    this.RaisePropertyChanged("passportId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string patronymic {
            get {
                return this.patronymicField;
            }
            set {
                if ((object.ReferenceEquals(this.patronymicField, value) != true)) {
                    this.patronymicField = value;
                    this.RaisePropertyChanged("patronymic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MainService.IAdminService")]
    public interface IAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/Test", ReplyAction="http://tempuri.org/IAdminService/TestResponse")]
        string Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/Test", ReplyAction="http://tempuri.org/IAdminService/TestResponse")]
        System.Threading.Tasks.Task<string> TestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddAdimn", ReplyAction="http://tempuri.org/IAdminService/AddAdimnResponse")]
        void AddAdimn(Client.MainService.AdminDto admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddAdimn", ReplyAction="http://tempuri.org/IAdminService/AddAdimnResponse")]
        System.Threading.Tasks.Task AddAdimnAsync(Client.MainService.AdminDto admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/EditAdmin", ReplyAction="http://tempuri.org/IAdminService/EditAdminResponse")]
        void EditAdmin(int id, Client.MainService.AdminDto admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/EditAdmin", ReplyAction="http://tempuri.org/IAdminService/EditAdminResponse")]
        System.Threading.Tasks.Task EditAdminAsync(int id, Client.MainService.AdminDto admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/getAllAdmins", ReplyAction="http://tempuri.org/IAdminService/getAllAdminsResponse")]
        Client.MainService.AdminDto[] getAllAdmins();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/getAllAdmins", ReplyAction="http://tempuri.org/IAdminService/getAllAdminsResponse")]
        System.Threading.Tasks.Task<Client.MainService.AdminDto[]> getAllAdminsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddEmployee", ReplyAction="http://tempuri.org/IAdminService/AddEmployeeResponse")]
        void AddEmployee(Client.MainService.EmployeeDto employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddEmployee", ReplyAction="http://tempuri.org/IAdminService/AddEmployeeResponse")]
        System.Threading.Tasks.Task AddEmployeeAsync(Client.MainService.EmployeeDto employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/EditEmployee", ReplyAction="http://tempuri.org/IAdminService/EditEmployeeResponse")]
        void EditEmployee(int id, Client.MainService.EmployeeDto employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/EditEmployee", ReplyAction="http://tempuri.org/IAdminService/EditEmployeeResponse")]
        System.Threading.Tasks.Task EditEmployeeAsync(int id, Client.MainService.EmployeeDto employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/DeleteEmployee", ReplyAction="http://tempuri.org/IAdminService/DeleteEmployeeResponse")]
        void DeleteEmployee(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/DeleteEmployee", ReplyAction="http://tempuri.org/IAdminService/DeleteEmployeeResponse")]
        System.Threading.Tasks.Task DeleteEmployeeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddPayment", ReplyAction="http://tempuri.org/IAdminService/AddPaymentResponse")]
        void AddPayment(Client.MainService.PaymentDto payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddPayment", ReplyAction="http://tempuri.org/IAdminService/AddPaymentResponse")]
        System.Threading.Tasks.Task AddPaymentAsync(Client.MainService.PaymentDto payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/EditPayment", ReplyAction="http://tempuri.org/IAdminService/EditPaymentResponse")]
        void EditPayment(int id, Client.MainService.PaymentDto payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/EditPayment", ReplyAction="http://tempuri.org/IAdminService/EditPaymentResponse")]
        System.Threading.Tasks.Task EditPaymentAsync(int id, Client.MainService.PaymentDto payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/DeletePayment", ReplyAction="http://tempuri.org/IAdminService/DeletePaymentResponse")]
        void DeletePayment(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/DeletePayment", ReplyAction="http://tempuri.org/IAdminService/DeletePaymentResponse")]
        System.Threading.Tasks.Task DeletePaymentAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddShift", ReplyAction="http://tempuri.org/IAdminService/AddShiftResponse")]
        void AddShift(Client.MainService.ShiftDto shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddShift", ReplyAction="http://tempuri.org/IAdminService/AddShiftResponse")]
        System.Threading.Tasks.Task AddShiftAsync(Client.MainService.ShiftDto shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/EditShift", ReplyAction="http://tempuri.org/IAdminService/EditShiftResponse")]
        void EditShift(int id, Client.MainService.ShiftDto shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/EditShift", ReplyAction="http://tempuri.org/IAdminService/EditShiftResponse")]
        System.Threading.Tasks.Task EditShiftAsync(int id, Client.MainService.ShiftDto shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/DeleteShift", ReplyAction="http://tempuri.org/IAdminService/DeleteShiftResponse")]
        void DeleteShift(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/DeleteShift", ReplyAction="http://tempuri.org/IAdminService/DeleteShiftResponse")]
        System.Threading.Tasks.Task DeleteShiftAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddViolation", ReplyAction="http://tempuri.org/IAdminService/AddViolationResponse")]
        void AddViolation(Client.MainService.ViolationDto violation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddViolation", ReplyAction="http://tempuri.org/IAdminService/AddViolationResponse")]
        System.Threading.Tasks.Task AddViolationAsync(Client.MainService.ViolationDto violation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/EditViolation", ReplyAction="http://tempuri.org/IAdminService/EditViolationResponse")]
        void EditViolation(int id, Client.MainService.ViolationDto violation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/EditViolation", ReplyAction="http://tempuri.org/IAdminService/EditViolationResponse")]
        System.Threading.Tasks.Task EditViolationAsync(int id, Client.MainService.ViolationDto violation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/DeleteViolation", ReplyAction="http://tempuri.org/IAdminService/DeleteViolationResponse")]
        void DeleteViolation(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/DeleteViolation", ReplyAction="http://tempuri.org/IAdminService/DeleteViolationResponse")]
        System.Threading.Tasks.Task DeleteViolationAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddViolationType", ReplyAction="http://tempuri.org/IAdminService/AddViolationTypeResponse")]
        void AddViolationType(Client.MainService.ViolationTypeDto violationType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddViolationType", ReplyAction="http://tempuri.org/IAdminService/AddViolationTypeResponse")]
        System.Threading.Tasks.Task AddViolationTypeAsync(Client.MainService.ViolationTypeDto violationType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/EditViolationType", ReplyAction="http://tempuri.org/IAdminService/EditViolationTypeResponse")]
        void EditViolationType(int id, Client.MainService.ViolationTypeDto violationType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/EditViolationType", ReplyAction="http://tempuri.org/IAdminService/EditViolationTypeResponse")]
        System.Threading.Tasks.Task EditViolationTypeAsync(int id, Client.MainService.ViolationTypeDto violationType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/DeleteViolationType", ReplyAction="http://tempuri.org/IAdminService/DeleteViolationTypeResponse")]
        void DeleteViolationType(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/DeleteViolationType", ReplyAction="http://tempuri.org/IAdminService/DeleteViolationTypeResponse")]
        System.Threading.Tasks.Task DeleteViolationTypeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddViolator", ReplyAction="http://tempuri.org/IAdminService/AddViolatorResponse")]
        void AddViolator(Client.MainService.ViolatorDto violator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AddViolator", ReplyAction="http://tempuri.org/IAdminService/AddViolatorResponse")]
        System.Threading.Tasks.Task AddViolatorAsync(Client.MainService.ViolatorDto violator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/EditViolator", ReplyAction="http://tempuri.org/IAdminService/EditViolatorResponse")]
        void EditViolator(int id, Client.MainService.ViolatorDto violator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/EditViolator", ReplyAction="http://tempuri.org/IAdminService/EditViolatorResponse")]
        System.Threading.Tasks.Task EditViolatorAsync(int id, Client.MainService.ViolatorDto violator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/DeleteViolator", ReplyAction="http://tempuri.org/IAdminService/DeleteViolatorResponse")]
        void DeleteViolator(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/DeleteViolator", ReplyAction="http://tempuri.org/IAdminService/DeleteViolatorResponse")]
        System.Threading.Tasks.Task DeleteViolatorAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminServiceChannel : Client.MainService.IAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceClient : System.ServiceModel.ClientBase<Client.MainService.IAdminService>, Client.MainService.IAdminService {
        
        public AdminServiceClient() {
        }
        
        public AdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Test() {
            return base.Channel.Test();
        }
        
        public System.Threading.Tasks.Task<string> TestAsync() {
            return base.Channel.TestAsync();
        }
        
        public void AddAdimn(Client.MainService.AdminDto admin) {
            base.Channel.AddAdimn(admin);
        }
        
        public System.Threading.Tasks.Task AddAdimnAsync(Client.MainService.AdminDto admin) {
            return base.Channel.AddAdimnAsync(admin);
        }
        
        public void EditAdmin(int id, Client.MainService.AdminDto admin) {
            base.Channel.EditAdmin(id, admin);
        }
        
        public System.Threading.Tasks.Task EditAdminAsync(int id, Client.MainService.AdminDto admin) {
            return base.Channel.EditAdminAsync(id, admin);
        }
        
        public Client.MainService.AdminDto[] getAllAdmins() {
            return base.Channel.getAllAdmins();
        }
        
        public System.Threading.Tasks.Task<Client.MainService.AdminDto[]> getAllAdminsAsync() {
            return base.Channel.getAllAdminsAsync();
        }
        
        public void AddEmployee(Client.MainService.EmployeeDto employee) {
            base.Channel.AddEmployee(employee);
        }
        
        public System.Threading.Tasks.Task AddEmployeeAsync(Client.MainService.EmployeeDto employee) {
            return base.Channel.AddEmployeeAsync(employee);
        }
        
        public void EditEmployee(int id, Client.MainService.EmployeeDto employee) {
            base.Channel.EditEmployee(id, employee);
        }
        
        public System.Threading.Tasks.Task EditEmployeeAsync(int id, Client.MainService.EmployeeDto employee) {
            return base.Channel.EditEmployeeAsync(id, employee);
        }
        
        public void DeleteEmployee(int id) {
            base.Channel.DeleteEmployee(id);
        }
        
        public System.Threading.Tasks.Task DeleteEmployeeAsync(int id) {
            return base.Channel.DeleteEmployeeAsync(id);
        }
        
        public void AddPayment(Client.MainService.PaymentDto payment) {
            base.Channel.AddPayment(payment);
        }
        
        public System.Threading.Tasks.Task AddPaymentAsync(Client.MainService.PaymentDto payment) {
            return base.Channel.AddPaymentAsync(payment);
        }
        
        public void EditPayment(int id, Client.MainService.PaymentDto payment) {
            base.Channel.EditPayment(id, payment);
        }
        
        public System.Threading.Tasks.Task EditPaymentAsync(int id, Client.MainService.PaymentDto payment) {
            return base.Channel.EditPaymentAsync(id, payment);
        }
        
        public void DeletePayment(int id) {
            base.Channel.DeletePayment(id);
        }
        
        public System.Threading.Tasks.Task DeletePaymentAsync(int id) {
            return base.Channel.DeletePaymentAsync(id);
        }
        
        public void AddShift(Client.MainService.ShiftDto shift) {
            base.Channel.AddShift(shift);
        }
        
        public System.Threading.Tasks.Task AddShiftAsync(Client.MainService.ShiftDto shift) {
            return base.Channel.AddShiftAsync(shift);
        }
        
        public void EditShift(int id, Client.MainService.ShiftDto shift) {
            base.Channel.EditShift(id, shift);
        }
        
        public System.Threading.Tasks.Task EditShiftAsync(int id, Client.MainService.ShiftDto shift) {
            return base.Channel.EditShiftAsync(id, shift);
        }
        
        public void DeleteShift(int id) {
            base.Channel.DeleteShift(id);
        }
        
        public System.Threading.Tasks.Task DeleteShiftAsync(int id) {
            return base.Channel.DeleteShiftAsync(id);
        }
        
        public void AddViolation(Client.MainService.ViolationDto violation) {
            base.Channel.AddViolation(violation);
        }
        
        public System.Threading.Tasks.Task AddViolationAsync(Client.MainService.ViolationDto violation) {
            return base.Channel.AddViolationAsync(violation);
        }
        
        public void EditViolation(int id, Client.MainService.ViolationDto violation) {
            base.Channel.EditViolation(id, violation);
        }
        
        public System.Threading.Tasks.Task EditViolationAsync(int id, Client.MainService.ViolationDto violation) {
            return base.Channel.EditViolationAsync(id, violation);
        }
        
        public void DeleteViolation(int id) {
            base.Channel.DeleteViolation(id);
        }
        
        public System.Threading.Tasks.Task DeleteViolationAsync(int id) {
            return base.Channel.DeleteViolationAsync(id);
        }
        
        public void AddViolationType(Client.MainService.ViolationTypeDto violationType) {
            base.Channel.AddViolationType(violationType);
        }
        
        public System.Threading.Tasks.Task AddViolationTypeAsync(Client.MainService.ViolationTypeDto violationType) {
            return base.Channel.AddViolationTypeAsync(violationType);
        }
        
        public void EditViolationType(int id, Client.MainService.ViolationTypeDto violationType) {
            base.Channel.EditViolationType(id, violationType);
        }
        
        public System.Threading.Tasks.Task EditViolationTypeAsync(int id, Client.MainService.ViolationTypeDto violationType) {
            return base.Channel.EditViolationTypeAsync(id, violationType);
        }
        
        public void DeleteViolationType(int id) {
            base.Channel.DeleteViolationType(id);
        }
        
        public System.Threading.Tasks.Task DeleteViolationTypeAsync(int id) {
            return base.Channel.DeleteViolationTypeAsync(id);
        }
        
        public void AddViolator(Client.MainService.ViolatorDto violator) {
            base.Channel.AddViolator(violator);
        }
        
        public System.Threading.Tasks.Task AddViolatorAsync(Client.MainService.ViolatorDto violator) {
            return base.Channel.AddViolatorAsync(violator);
        }
        
        public void EditViolator(int id, Client.MainService.ViolatorDto violator) {
            base.Channel.EditViolator(id, violator);
        }
        
        public System.Threading.Tasks.Task EditViolatorAsync(int id, Client.MainService.ViolatorDto violator) {
            return base.Channel.EditViolatorAsync(id, violator);
        }
        
        public void DeleteViolator(int id) {
            base.Channel.DeleteViolator(id);
        }
        
        public System.Threading.Tasks.Task DeleteViolatorAsync(int id) {
            return base.Channel.DeleteViolatorAsync(id);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MainService.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddPaymentUser", ReplyAction="http://tempuri.org/IUserService/AddPaymentUserResponse")]
        void AddPaymentUser(Client.MainService.PaymentDto payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddPaymentUser", ReplyAction="http://tempuri.org/IUserService/AddPaymentUserResponse")]
        System.Threading.Tasks.Task AddPaymentUserAsync(Client.MainService.PaymentDto payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/EditPaymentUser", ReplyAction="http://tempuri.org/IUserService/EditPaymentUserResponse")]
        void EditPaymentUser(int id, Client.MainService.PaymentDto payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/EditPaymentUser", ReplyAction="http://tempuri.org/IUserService/EditPaymentUserResponse")]
        System.Threading.Tasks.Task EditPaymentUserAsync(int id, Client.MainService.PaymentDto payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeletePaymentUser", ReplyAction="http://tempuri.org/IUserService/DeletePaymentUserResponse")]
        void DeletePaymentUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeletePaymentUser", ReplyAction="http://tempuri.org/IUserService/DeletePaymentUserResponse")]
        System.Threading.Tasks.Task DeletePaymentUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddShiftUser", ReplyAction="http://tempuri.org/IUserService/AddShiftUserResponse")]
        void AddShiftUser(Client.MainService.ShiftDto shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddShiftUser", ReplyAction="http://tempuri.org/IUserService/AddShiftUserResponse")]
        System.Threading.Tasks.Task AddShiftUserAsync(Client.MainService.ShiftDto shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/EditShiftUser", ReplyAction="http://tempuri.org/IUserService/EditShiftUserResponse")]
        void EditShiftUser(int id, Client.MainService.ShiftDto shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/EditShiftUser", ReplyAction="http://tempuri.org/IUserService/EditShiftUserResponse")]
        System.Threading.Tasks.Task EditShiftUserAsync(int id, Client.MainService.ShiftDto shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteShiftUser", ReplyAction="http://tempuri.org/IUserService/DeleteShiftUserResponse")]
        void DeleteShiftUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteShiftUser", ReplyAction="http://tempuri.org/IUserService/DeleteShiftUserResponse")]
        System.Threading.Tasks.Task DeleteShiftUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddViolationUser", ReplyAction="http://tempuri.org/IUserService/AddViolationUserResponse")]
        void AddViolationUser(Client.MainService.ViolationDto violation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddViolationUser", ReplyAction="http://tempuri.org/IUserService/AddViolationUserResponse")]
        System.Threading.Tasks.Task AddViolationUserAsync(Client.MainService.ViolationDto violation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/EditViolationUser", ReplyAction="http://tempuri.org/IUserService/EditViolationUserResponse")]
        void EditViolationUser(int id, Client.MainService.ViolationDto violation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/EditViolationUser", ReplyAction="http://tempuri.org/IUserService/EditViolationUserResponse")]
        System.Threading.Tasks.Task EditViolationUserAsync(int id, Client.MainService.ViolationDto violation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteViolationUser", ReplyAction="http://tempuri.org/IUserService/DeleteViolationUserResponse")]
        void DeleteViolationUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteViolationUser", ReplyAction="http://tempuri.org/IUserService/DeleteViolationUserResponse")]
        System.Threading.Tasks.Task DeleteViolationUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddViolatorUser", ReplyAction="http://tempuri.org/IUserService/AddViolatorUserResponse")]
        void AddViolatorUser(Client.MainService.ViolatorDto violator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddViolatorUser", ReplyAction="http://tempuri.org/IUserService/AddViolatorUserResponse")]
        System.Threading.Tasks.Task AddViolatorUserAsync(Client.MainService.ViolatorDto violator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/EditViolatorUser", ReplyAction="http://tempuri.org/IUserService/EditViolatorUserResponse")]
        void EditViolatorUser(int id, Client.MainService.ViolatorDto violator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/EditViolatorUser", ReplyAction="http://tempuri.org/IUserService/EditViolatorUserResponse")]
        System.Threading.Tasks.Task EditViolatorUserAsync(int id, Client.MainService.ViolatorDto violator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteViolatorUser", ReplyAction="http://tempuri.org/IUserService/DeleteViolatorUserResponse")]
        void DeleteViolatorUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteViolatorUser", ReplyAction="http://tempuri.org/IUserService/DeleteViolatorUserResponse")]
        System.Threading.Tasks.Task DeleteViolatorUserAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : Client.MainService.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<Client.MainService.IUserService>, Client.MainService.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddPaymentUser(Client.MainService.PaymentDto payment) {
            base.Channel.AddPaymentUser(payment);
        }
        
        public System.Threading.Tasks.Task AddPaymentUserAsync(Client.MainService.PaymentDto payment) {
            return base.Channel.AddPaymentUserAsync(payment);
        }
        
        public void EditPaymentUser(int id, Client.MainService.PaymentDto payment) {
            base.Channel.EditPaymentUser(id, payment);
        }
        
        public System.Threading.Tasks.Task EditPaymentUserAsync(int id, Client.MainService.PaymentDto payment) {
            return base.Channel.EditPaymentUserAsync(id, payment);
        }
        
        public void DeletePaymentUser(int id) {
            base.Channel.DeletePaymentUser(id);
        }
        
        public System.Threading.Tasks.Task DeletePaymentUserAsync(int id) {
            return base.Channel.DeletePaymentUserAsync(id);
        }
        
        public void AddShiftUser(Client.MainService.ShiftDto shift) {
            base.Channel.AddShiftUser(shift);
        }
        
        public System.Threading.Tasks.Task AddShiftUserAsync(Client.MainService.ShiftDto shift) {
            return base.Channel.AddShiftUserAsync(shift);
        }
        
        public void EditShiftUser(int id, Client.MainService.ShiftDto shift) {
            base.Channel.EditShiftUser(id, shift);
        }
        
        public System.Threading.Tasks.Task EditShiftUserAsync(int id, Client.MainService.ShiftDto shift) {
            return base.Channel.EditShiftUserAsync(id, shift);
        }
        
        public void DeleteShiftUser(int id) {
            base.Channel.DeleteShiftUser(id);
        }
        
        public System.Threading.Tasks.Task DeleteShiftUserAsync(int id) {
            return base.Channel.DeleteShiftUserAsync(id);
        }
        
        public void AddViolationUser(Client.MainService.ViolationDto violation) {
            base.Channel.AddViolationUser(violation);
        }
        
        public System.Threading.Tasks.Task AddViolationUserAsync(Client.MainService.ViolationDto violation) {
            return base.Channel.AddViolationUserAsync(violation);
        }
        
        public void EditViolationUser(int id, Client.MainService.ViolationDto violation) {
            base.Channel.EditViolationUser(id, violation);
        }
        
        public System.Threading.Tasks.Task EditViolationUserAsync(int id, Client.MainService.ViolationDto violation) {
            return base.Channel.EditViolationUserAsync(id, violation);
        }
        
        public void DeleteViolationUser(int id) {
            base.Channel.DeleteViolationUser(id);
        }
        
        public System.Threading.Tasks.Task DeleteViolationUserAsync(int id) {
            return base.Channel.DeleteViolationUserAsync(id);
        }
        
        public void AddViolatorUser(Client.MainService.ViolatorDto violator) {
            base.Channel.AddViolatorUser(violator);
        }
        
        public System.Threading.Tasks.Task AddViolatorUserAsync(Client.MainService.ViolatorDto violator) {
            return base.Channel.AddViolatorUserAsync(violator);
        }
        
        public void EditViolatorUser(int id, Client.MainService.ViolatorDto violator) {
            base.Channel.EditViolatorUser(id, violator);
        }
        
        public System.Threading.Tasks.Task EditViolatorUserAsync(int id, Client.MainService.ViolatorDto violator) {
            return base.Channel.EditViolatorUserAsync(id, violator);
        }
        
        public void DeleteViolatorUser(int id) {
            base.Channel.DeleteViolatorUser(id);
        }
        
        public System.Threading.Tasks.Task DeleteViolatorUserAsync(int id) {
            return base.Channel.DeleteViolatorUserAsync(id);
        }
    }
}
