//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaiWcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public long id { get; set; }
        public int person_id { get; set; }
        public System.DateTime payday { get; set; }
        public bool is_paid { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
