//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaiWcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Violation
    {
        public int id { get; set; }
        public string violation_type_id { get; set; }
        public int person_id { get; set; }
        public string car_number { get; set; }
        public string protocol_id { get; set; }
        public System.DateTime date { get; set; }
        public float penalty { get; set; }
        public Nullable<float> latitude { get; set; }
        public Nullable<float> longitude { get; set; }
        public string address { get; set; }
        public string description { get; set; }
        public int shift_id { get; set; }
        public bool paid { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual ViolationType ViolationType { get; set; }
    }
}
