//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaiWcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Violation
    {
        public int id { get; set; }
        public string violation_type_id { get; set; }
        public Nullable<int> person_id { get; set; }
        public string car_number { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public float penalty { get; set; }
        public Nullable<float> location_n { get; set; }
        public Nullable<float> location_e { get; set; }
        public string address { get; set; }
        public string description { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ViolationType ViolationType { get; set; }
    }
}
